seed: 543
checkpoint_every: 1000
log_every_iters: 15
dataset_name: cifar10
data_path: /datasets
token_mixing_type: sep_hw_ln_c
in_channels: 3
layers:
  - depth: 4
    dim: 128
    patch_size: 4
expansion_factor: 4
dropout: 0.
batch_size: 512
num_workers: 2
lr: 0.001
weight_decay: 1e-4
num_epochs: 24
num_warmup_epochs: 4
validate_every: 1
stop_iteration:
project_name: pyramid-mixer
task_name: cifar10-test5
backend:
resume_from:
nproc_per_node:
with_clearml: True
with_amp: False