checkpoint_every: 1000
log_every_iters: 15
dataset_name: cifar10
data_path: /datasets
token_mixing_type: original_tm
in_channels: 3
layers:
  - depth: 4
    dim: 256
    patch_size: 4
expansion_factor: 4
shortcut: False
gap: True
dropout: 0.
mixup_alpha: 0.5
cutmix_alpha: 0.5
mixup_p: 0.8
cutmix_p: 1.0
label_smoothing_alpha: 0.1
batch_size: 512
num_workers: 2
lr: 0.001
end_lr: 1e-5
weight_decay: 0.05
num_epochs: 24
num_warmup_epochs: 4
validate_every: 1
stop_iteration:
project_name: s3c-mlp
task_name: cifar10-org-mixer
backend:
resume_from:
nproc_per_node:
with_clearml: True
with_amp: False