seed: 42
checkpoint_every: 1000
log_every_iters: 15
dataset_name: imagenet
data_path: /dataset/hoge_data
in_channels: 3
layers:
  - depth: 4
    dim: 384
    patch_size: 4
  - depth: 4
    dim: 768
    patch_size: 4
  - depth: 4
    dim: 3072
    patch_size: 7
expansion_factor: 4
dropout: 0.
batch_size: 512
num_workers: 20
lr: 0.001
weight_decay: 1e-4
num_epochs: 100
num_warmup_epochs: 10
validate_every: 1
stop_iteration:
project_name: pyramid-mixer
task_name: default
backend:
resume_from:
nproc_per_node:
with_clearml: True
with_amp: False