checkpoint_every: 1000
log_every_iters: 15
dataset_name: imagenet
data_path: /datasets/imagenet
token_mixing_type: sep_ln_codim_tm
in_channels: 3
layers:
  - depth: 4
    dim: 768
    patch_size: 16
  - depth: 4
    dim: 768
    patch_size: 2
  - depth: 2
    dim: 768
    patch_size: 2
  - depth: 2
    dim: 768
    patch_size: 2
expansion_factor: 4
shortcut: True
gap: False
dropout: 0.
mixup_alpha: 0.5
label_smoothing_alpha: 0.1
batch_size: 512
num_workers: 20
lr: 0.001
end_lr: 1e-5
weight_decay: 0.05
num_epochs: 155
num_warmup_epochs: 5
validate_every: 1
stop_iteration:
project_name: pyramid-mixer
task_name: default
backend:
resume_from:
nproc_per_node:
with_clearml: True
with_amp: False
